### ISSUE TITLE
Warning: mkdir(): Invalid path when src_path is empty

### ISSUE THREAD

**Issue by bartosz-zasada** [phpspec/phpspec#1065]
I've set `src_path` to an empty string, like this:
```
suites:
    main_suite:
        namespace: Bamiz\ScreamingWebshop
        psr4_prefix: Bamiz\ScreamingWebshop\
        src_path: ""
```
Generating classes and methods works fine. However, every time when I execute `run` or `desc` commands, I get the following warning:
`PHP Warning:  mkdir(): Invalid path in (...)/vendor/phpspec/phpspec/src/PhpSpec/Console/ContainerAssembler.php on line 393`
