### ISSUE TITLE
[RFC] Run PhpSpec for particular files from different suites

### ISSUE THREAD

**Issue by borNfreee** [phpspec/phpspec#1123]
Hello, I would like to propose and ask questions about a new feature that would be very useful performance wise for my tool.

## Problem

I'm working on Mutation Testing Framework (MTF) and it is known fact that after each mutation we need to run tests to see whether they are broken or not by mutated code.

https://en.wikipedia.org/wiki/Mutation_testing

Obviously, if you have **N** tests and **M** mutations, it requires **N*M** number of executed tests, which can take hours (literally).

## Solution

The simplest solution is to run _only those tests for each mutation, that covers mutated line of code_. This information is fetched from `CodeCoverage` and `xDebug` or `phpdbg` on the initial tests run and then used for each mutation.

For example, PHPUnit has it out of the box and we can define a set of test files need to be executed:

```xml
<testsuites>
    <testsuite name="Application Test Suite">
        <file>/absolute/path/to/file/WithTest.php</file>
        <file>relative/path/to/file/WithTest.php</file>
        ...
    </testsuite>
</testsuites>
```

### What does it bring to Mutation Testing Framework?

The main advantage of such approach is that mutation framework _does not depend on PHPUnit_. So we are not coupled to any version, we don't need any interfaces from it to implement some listeners to filter out tests. We don't have it in `composer.json`. (please read detailed explanation [here](https://github.com/infection/site/blob/master/src/guide/compare.md#dependencies-in-composerjson)).

We just run tests against this custom config and it dramatically reduces the time needed for each mutation (e.g. 2 tests would be executed instead of 1000).

So I want to have the same feature in PhpSpec that is supported by Mutation Testing Framework I'm working on.

Do you have any thoughts on this guys? I found that you [don't want to overload the resource locator](https://github.com/phpspec/phpspec/issues/876#issuecomment-193804590) but I would like to open this discussion again at least in the context of MTF.

Possible config settings:

```yml
suites:
    Application:
        namespace: Application
        spec_prefix: Spec
        src_path: module/Application/src/
        spec_path: module/Application/bundle
        files:
           - /path/to/fileSpec.php
           - relative/path/toSpec.php
           # or even related to spec_path
          - file3WithSpec.php # module/Application/bundle/file3WithSpec.php
```

Related issues:

* https://github.com/phpspec/phpspec/pull/850

Maybe you can advise other ways of filtering out not needed tests like tagging or stream wrappers or any other solution I'm not aware of.

Initially, I thought I can achieve this by providing command arguments for PhpSpec but seems like it's impossible because of limitations of current resource loader and command line length limits in different OSs.
