### ISSUE TITLE
No line number in syntax error

### ISSUE THREAD

**Issue by jleaders** [phpspec/phpspec#1217]
At command line I run
```
$ bin/phpspec run                                                                                                                                                                          

```

And the output is:
```
      PSM\Business\Client

 119  ! Loading specification
        exception [err:ParseError("syntax error, unexpected '}', expecting ';'")] has been thrown.

----  broken examples

        PSM/Business/Client
 119  ! Loading specification
        exception [err:ParseError("syntax error, unexpected '}', expecting ';'")] has been thrown.


1 specs
1 examples (1 broken)
5ms

```

I'm sure my code has a syntax error, however this bug is showing that there is no line number showing in the ParseError. **How will I ever track down errors without a line number?**

I tried with & without formatter: pretty

**phpspec.yml**
```
suites:
    default:
        namespace: PSM\Business
        psr4_prefix: PSM\Business
#formatter.name: pretty
```
