### ISSUE TITLE
Detect spec dir when setted composer_suite_detection

### ISSUE THREAD

**Issue by timiTao** [phpspec/phpspec#1249]
# Aim

I try to work with monorepo. I have few `packages` and all of them have spec tests.
I want to hold specs in each `package` - not in main dir.

# Problem
 When I set `composer_suite_detection: true`, then [code will generate](https://github.com/phpspec/phpspec/blob/master/src/PhpSpec/Console/ContainerAssembler.php#L440-L445) equal code to this configuration:
```
suites:
  aggrego_commandconsumer_suite:
    spec_path: . #main dir
    src_path: packages/Aggrego/CommandConsumer/src
    namespace: Aggrego\CommandConsumer
    psr4_prefix: Aggrego\CommandConsumer
```

Regardless, I have in `composer.json`:
```
    "autoload": {
        "exclude-from-classmap": [
            "packages/Aggrego/CommandConsumer/spec/"
        ],
        "psr-4": {
            "Aggrego\\CommandConsumer\\": "packages/Aggrego/CommandConsumer/src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "spec\\Aggrego\\CommandConsumer\\": "packages/Aggrego/CommandConsumer/spec/"
        }
    },
```

To solve this, I need manually set this in `phpspec.yml`:
```
suites:
  aggrego_commandconsumer_suite:
    spec_path: packages/Aggrego/CommandConsumer
    src_path: packages/Aggrego/CommandConsumer/src
    namespace: Aggrego\CommandConsumer
    psr4_prefix: Aggrego\CommandConsumer
```

# Solution

Search if the namespace is set in autoloader `spec_prefix` + `namespace`, and if `true` then set also `spec_path` for that namespace. This should also work with multi-namespaces :)

# Summary

What do you think?
I can make this PR.
