### ISSUE TITLE
Trying to set root directory as src

### ISSUE THREAD

**Issue by AnFox** [phpspec/phpspec#1364]
I have this project structure:

```
www
-- controllers
-- models
-- services
---- SomeService.php
-- bin
---- phpspec
-- spec
---- services
------ SomeServiceSpec.php
-- phpspec.yml
 ```

I want to use `SomeServiceSpec.php` to test `SomeService.php`.
My `phpspec.yml`:
```
formatter.name: pretty
suites:
    default:
      namespace: app
      psr4_prefix: app
      src_path: ./
```

When I do `bin/phpspec run' I have the error `class app\services\SomeService does not exist.`.
Then it asks if I want it to be created. If I agree it ask if I want it to be **overwritten**!

I was trying to set `src_path` as `.` or `/` but it does not help.
