### ISSUE TITLE
PSR4 - Collaborator does not exist?

### ISSUE THREAD

**Issue by Saeven** [phpspec/phpspec#1384]
PHP 8.0.7 (cli) (built: Jun  4 2021 03:50:01) ( NTS )
kern.version: Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64
phpspec/phpspec 7.1.0

### Setup

Here's a barebones Laminas composer setup, created with:
`composer create-project -sdev laminas/laminas-mvc-skeleton phpspec-test`

To which I have:

* added phpspec to composer.json
* have added phpspec.yml with psr4_prefix
* have added Application\Service\TestService (just a constructor)

With this in place, I issued:

    ./vendor/bin/phpspec desc Application/Service/TestService

And the spec was created in the right place. So far so good.

### Config

_phpspec.yml_
```
suites:
  Application:
    namespace: Application
    spec_prefix: Spec
    psr4_prefix: Application
    spec_path: module/Application/spec
    src_path: module/Application/src/
formatter.name: pretty
```

_module/Application/spec/Spec/Service/TestServiceSpec.php_
```
<?php

namespace Spec\Application\Service;

use Application\Service\TestService;
use Interop\Container\ContainerInterface;
use PhpSpec\ObjectBehavior;

class TestServiceSpec extends ObjectBehavior
{
    function let(
        ContainerInterface $container
    ){
        $this->beConstructedWith($container);
    }

    function it_is_initializable()
    {
        $this->shouldHaveType(TestService::class);
    }
}
```

Then issuing `./vendor/bin/phpspec run` I get

```
      Application\Service\TestService

  17  ! is initializable
        collaborator does not exist : Spec\Application\Service\ContainerInterface
```

Help appreciated! I'm stumped.

[phpspec-test.zip](https://github.com/phpspec/phpspec/files/6772833/phpspec-test.zip)
