### ISSUE TITLE
Documentation needed: phpspec.yml does not different PSRs in different suites

### ISSUE THREAD

**Issue by ash-m** [phpspec/phpspec#1468]
So, I just started throwing some misc classes in my `fake/` directory. They are just minimal interface implementations so I didn't care to reflect where they might go in the `src/` directory if they were real classes. But adding `"Fake\\": "fake/"` to `composer.json` would mean that the specs for these classes would be in `spec/`, which I felt would be confusing. Solution? PSR-0. Now they get their own directory, `spec/Fake`. But if you have a `psr4_prefix` mapping in your `phpspec.yml` configuration, then phpspec won't be able to find the class, claiming it must be in "the base spec namespace `spec\App\`".

Here' s part of my `composer.json`:
```json
  "autoload": {
    "psr-4": {
      "App\\": "src/"
    },
    "psr-0": {
      "Fake\\": "fake/"
    }
  }
```

Here's my `phpspec.yml`:
```yaml
suites:
  fake: 
    namespace: Fake
    src_path: fake
  default:
    namespace: App
    psr4_prefix: App
    src_path: src
```

Here's what I ran:
```sh-session
0d209c8f2ff3:/app# php vendor/bin/phpspec desc Fake/Foo
Specification for Fake\Foo created in /app/spec/Fake/FooSpec.php.

0d209c8f2ff3:/app# php vendor/bin/phpspec run Fake/Foo
                                                                                 0
0 specs
0 examples
0ms

0d209c8f2ff3:/app# php vendor/bin/phpspec run spec/Fake/FooSpec.php

In PSR0Locator.php line 300:

  Spec class `spec\Fake\FooSpec` must be in the base spec namespace `spec\App\`.


run [-f|--format FORMAT] [--stop-on-failure] [--no-code-generation] [--no-rerun] [--fake] [-b|--bootstrap BOOTSTRAP] [--] [<spec>]

0d209c8f2ff3:/app#
```

Although this does sort of make it seem like the concept of a `suite` is not isolated, this isn't a huge problem. I don't _really_ need to do this, but it would've been nice to have it documented.

**Comment by ash-m** [comment]
Actually, it would seem if _any_ suite has the `psr4_prefix` then it seems to only pick one for the root namespace. How this decision is made escapes me.

**Comment by ash-m** [comment]
Work around: use a separate config file for different PSR-4 suites. 

If anyone comes across this, here's the config I used to map `./fake/<classes>` to `./spec/Fake/<specs>`
```yaml
suites:
  fake: 
    namespace: Fake
    spec_prefix: ""
    spec_path: ./spec/Fake
    src_path: fake
    psr4_prefix: Fake
```

(although your specs will not have the `spec` prefix)
