### ISSUE TITLE
phpspec reads only the last suite, when no namespace provided

### ISSUE THREAD

**Issue by paulodiovani** [phpspec/phpspec#384]
When I have multiple suites with no namespace provided for each -- common for legacy/old systems (php < 5.3) -- the `describe` command reads only the last suite.

Exemple `phpspec.yml`:

```
suites:
    multi24_libs:
        spec_prefix: "spec\my_app\libraries"
        src_path: "../sistemas/my_app/application/libraries/"

    multi24_models:
        spec_prefix: "spec\my_app\models"
        src_path: "../sistemas/my_app/application/models/"

formatter.name: pretty
```

This affects the following cases:
- generate Spec classes (with `phpspec describe`)
- generate class or method for incomplete classes (with `phpspec run` without `--no-interaction` option)

More details can be found at [this stackoverflow question](http://stackoverflow.com/questions/24680644/phpspec-with-multiple-suites-only-consider-the-last-one)
