### ISSUE TITLE
RC2 does not find any specs

### ISSUE THREAD

**Issue by sagikazarmark** [phpspec/phpspec#572]
After upgrading to RC2, phpspec does not find/run any specs. Tried with manually setting the config file, tried with pointing to the specs folder and a specific spec as well.

Don't get any error messages, just no specs are run.

Are there any upgrade steps needed?

Config file for reference:

``` yaml
suites:
  http_suite:
    namespace: Indigo\Http
    psr4_prefix: Indigo\Http
extensions:
  - PhpSpec\Extension\CodeCoverageExtension
formatter.name: pretty
code_coverage:
  output: build/coverage/
```

(code coverage extension is installed)
