### ISSUE TITLE
Problem when running spec suites from CLI

### ISSUE THREAD

**Issue by mirfilip** [phpspec/phpspec#641]
After updating from `2.0.*` to `2.1.*`, there is a problem when running specs from CLI.

# Project details
Directory structure
```
+-- phpspec.yml.dist
+-- module
|   +-- Api
|        +-- src
|   +-- Ovp
|        +-- src
+-- tests
|   +-- unit
|   +-- features
|   +-- spec
|        +-- Api
|        +-- Ovp
```
composer.json autoloading part
```
"autoload": {
        "psr-0": {
            "Api": "module/Api/src",
            "Ovp": "module/Ovp/src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Behat\\": "tests/features/src"
        },
        "psr-0": {
            "": "tests/unit"
        }
    }
```

phpspec.yml.dist
```
code_generator.templates.paths:
  - tests/spec/templates

suites:
  ovp:
    namespace: Ovp
    src_path: module/Ovp/src
    spec_path: tests
  api:
    namespace: Api
    src_path: module/Api/src
    spec_path: tests

formatter.name: pretty
```

# Problem
Running single test from CLI using `2.0.*`:
```
> pwd // I'm in a project root
> phpspec run tests/spec/Api/Config/ProviderContextSpec.php // One of existing tests
> (...)
1 specs
2 examples (1 passed, 1 broken)
14ms
```

Running single test from CLI using `2.1.*`:
```
> pwd // I'm in a project root
> phpspec run tests/spec/Api/Config/ProviderContextSpec.php // One of existing tests
> (...)
[RuntimeException]
  Spec class must be in the base spec namespace `spec\Ovp\`.
```
I noticed that when I comment out `ovp` suite, everything works well.
What happens ? Is there anything wrong with suites configuration ?
