### ISSUE TITLE
Impossible to run single spec file

### ISSUE THREAD

**Issue by Anahkiasen** [phpspec/phpspec#675]
I have the following structure:

```
| app
| -- Foo
| ---- Bar
| ------ SomeClass.php
| -- tests
| ---- Bar
| ------ SomeClassSpec.php
```

**composer.json**
```json
"autoload": {
	"psr-4": {
		"Foo\\": "app/Foo",
	}
},
"autoload-dev": {
	"psr-4": {
		"Foo\\": "app/tests"
	}
},
```

**phpspec.yaml**
```yaml
suites:
    Foo:
        namespace: Foo
        psr4_prefix: Foo
        spec_prefix: ''
        src_path: app
        spec_path: app/tests
```

Now:
- When I run `phpspec run`, everything is fine
- If I run `phpspec run app/tests/Foo/Bar` it works
- But if I run `phpspec run app/tests/Foo/Bar/SomeClassSpec.php` it just says:

```
0 specs
0 examples
0ms
```

I tried doing `phpspec describe Foo/Bar/SomeClass` and it tells me I already have a spec and asks me if I want to overwrite it so I assume it's at the right place and all. Am I doing something wrong or is this a bug?
