### ISSUE TITLE
Different spec namespace structure

### ISSUE THREAD

**Issue by maryo** [phpspec/phpspec#806]
Hi. Looks like currently the only supported namespace structure is by using prefix.
This is from the documentation:
`spec_prefix` [default: spec] - The namespace prefix for specifications. The complete namespace for specifications is `%spec_prefix%\%namespace%`;

I'd love to achieve this structure:
The SUT class is located under `src/FooBundle/Command/ReplyToOfferHandler.php`
It's FQN is `FooBundle\Command\ReplyToOfferHandler`

I'd like the spec file to be located under
`src/FooBundle/Tests/Command/ReplyToOfferHandlerSpec.php
with corresponding FQN: `FooBundle\Tests\Command\ReplyToOfferHandlerSpec`

I can set `phpspec.yml` to
```yml
suites:
    foo_bundle:
        namespace: FooBundle
        psr4_prefix: FooBundle
        src_path: src
        spec_path: src
        spec_prefix: Foo\Tests
```
This configuration results in the directory structure I want but not the namespace one because the spec namespace is then `FooBundle\Tests\FooBundle\Command`. The namespace then contains the `FooBundle` twice.

I think that what I want to achieve is quite logical. This is actually a common Symfony2 tests structure.

This seems impossible to do using the prefix. But I'm not sure what to propose instead.
