### ISSUE TITLE
Configure phpspec with codeiginter 

### ISSUE THREAD

**Issue by agarhy** [phpspec/phpspec#846]
I'm trying to configure phpspec to work with codeiginter 3

here is the composer.json
```
{
	"description": "The CodeIgniter framework",
	"name": "codeigniter/framework",
......
	"require-dev": {
		"mikey179/vfsStream": "1.1.*",
                "phpspec/phpspec": "~2.0"
	},
        "autoload":{
            "psr-4":{
                "":"application"
            }
        }
}
```

and phpspec.yaml

```
suites:
    controllers:
        namespace: 
        src_path: application
        spec_path: application

bootstrap: spec/ci_bootstrap.php

```

Spec test file are being created properly in application/spec/controllers
And when run phpspec it creates the controller class in application/controllers

but seems can not find controller class when running and keep showing 
```
 Do you want me to create `controllers\movies` for you?
```

tried to use ci_bootstrap.php file as in this article http://blog.anidear.com/2012/11/using-phpspec-with-codeigniter.html
but it's not working seems supporting only phpspec-v1

any idea how can properly run phpspec2 with codeiginter 3 ?

Codeiginter file structure is 

Application
``controllers
``views
System
``core
Vendor
``phpspec
