### ISSUE TITLE
Open to a PR to use Suite name to run the specs it contains?

### ISSUE THREAD

**Issue by Saeven** [phpspec/phpspec#849]
For example, in my phpspec.yml, I have:

```
suites:
    Application:
        namespace: Application
        spec_prefix: Spec
        src_path: module/Application/src/
        spec_path: module/Application/bundle
```

I'd like to be able to just:

> ./phpspec run -sApplication 
   
or

> ./phpspec run --suite Application         

Some such... I can get cracking on a fork if you're open to the idea

Thanks!
